### ISSUE TITLE
Installation failed with message INSTALL_FAILED_MISSING_SHARED_LIBRARY:

### ISSUE THREAD

**Issue by mohsinabid** [ZebraDevs/EMDK-Android-Samples#1]
From here I have setup the EMDK
http://techdocs.zebra.com/emdk-for-android/7-3/guide/setup/

When I am using this tag in manifest in barcodesample1 from your github example
https://github.com/Zebra/samples-emdkforandroid-7_3

<uses-library android:name="com.symbol.emdk" android:required="true"/>

Then Application does not get installed.

And if I change the value from true to false it get installed but app crashes and I get these errors.

2019-06-13 18:54:29.071 11328-11328/com.symbol.barcodesample1 E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.symbol.barcodesample1, PID: 11328
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.symbol.barcodesample1/com.symbol.barcodesample1.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.symbol.barcodesample1.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.symbol.barcodesample1-Y11NujkCJicTE2fSXraWSA==/base.apk"],nativeLibraryDirectories=[/data/app/com.symbol.barcodesample1-Y11NujkCJicTE2fSXraWSA==/lib/x86, /system/lib]]
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.symbol.barcodesample1.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.symbol.barcodesample1-Y11NujkCJicTE2fSXraWSA==/base.apk"],nativeLibraryDirectories=[/data/app/com.symbol.barcodesample1-Y11NujkCJicTE2fSXraWSA==/lib/x86, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:193) 
at android.app.ActivityThread.main(ActivityThread.java:6669) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/symbol/emdk/EMDKManager$EMDKListener;
at java.lang.VMClassLoader.findLoadedClass(Native Method)
at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
... 15 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.symbol.emdk.EMDKManager$EMDKListener" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.symbol.barcodesample1-Y11NujkCJicTE2fSXraWSA==/base.apk"],nativeLibraryDirectories=[/data/app/com.symbol.barcodesample1-Y11NujkCJicTE2fSXraWSA==/lib/x86, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 18 more

Kindly tell me whats the issues and what should I do to solve this issue.

![Capture](https://user-images.githubusercontent.com/24939489/59499758-7aaca080-8eb1-11e9-9c47-93b1f1df793b.PNG)
@benhorgen  @darryncampbell  @cfh463 Can you answer this

**Comment by PassionateSolutions** [comment]
I am getting the same error.  No one has replied to this issue on here?  How is that so?

**Comment by gilbertgit** [comment]
Has anyone made any progress on this??? For me, it doesn't happen every time I load the app. Only on occasion. I have not noticed a pattern. I'm using a TC77 device with the latest version of the EMDK from the plugin manager in Android studio. The device itself seems to be running EMDK version 7.2.2.2202. 
I've tried moving the EMDKListner to a separate class (EMDKWrapper) and instantiating that class after my Activity has loaded but I still get ClassNotFoundException.
I also have `multiDexEnabled` set to true and required set to false on the `uses-library` property in my manifest.
Some help on this would be greatly appreciated!

**Comment by darryncampbell** [comment]
Is this reproducible with a sample app?  Or does it require modifying the sample app in some way?  Also, which Android version and security patch level is the device running?

**Comment by gilbertgit** [comment]
The device is running Android 8.1.0 with the the security patch from Jan 1, 2019. For me, it's on custom code. I have not ran the sample app yet.

**Comment by vojtechvosmik** [comment]
Same issue here. Is it finally fixed?

**Comment by danutdumitru** [comment]
I had a similar problem -> I fixed it by adding

`<uses-library android:name="com.symbol.emdk"/> `

into AndroidManifest.xml file

**Comment by developer1-makesure** [comment]
> I had a similar problem -> I fixed it by adding
> 
> `<uses-library android:name="com.symbol.emdk"/> `
> 
> into AndroidManifest.xml file

I am trying to do the same still the error occurs

**Comment by darryncampbell** [comment]
Please take a look at the Getting Started guides to set up EMDK with Android Studio and build a 'Hello EMDK' app (https://techdocs.zebra.com/emdk-for-android/7-6/guide/gettingstarted/).  There is also a sample app available from https://techdocs.zebra.com/emdk-for-android/7-6/samples/barcode/ .  Please also bear in mind that the EMDK will only work on Zebra devices.  I see a few problem reports under this same issue so if the above steps do not resolve any problem, I recommend posting to the developer portal at developer.zebra.com which is monitored more closely than this repository.

**Comment by danutdumitru** [comment]
> > I had a similar problem -> I fixed it by adding
> > `<uses-library android:name="com.symbol.emdk"/> `
> > into AndroidManifest.xml file
> 
> I am trying to do the same still the error occurs

My AndroidManifest.xml looks like  :

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="...">

    <uses-permission android:name="com.symbol.emdk.permission.EMDK" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
	<uses-library android:name="com.symbol.emdk" />
        <activity
            .../>
        <activity
            ... />
        <activity
            android:name=".MainActivity"
            ....
        </activity>
    </application>

</manifest>
```

The lines that fixed the issue for me are:

```
<uses-permission android:name="com.symbol.emdk.permission.EMDK" />
 <uses-library android:name="com.symbol.emdk" />
```

I also added the dependency into build.gradle file of the module:


```
dependencies {
...
   compileOnly 'com.symbol:emdk:+'
...
}
```

**Comment by NareshMittal** [comment]
For me, just adding the above two lines (shown below also) fixed the issue. -
   <uses-permission android:name="com.symbol.emdk.permission.EMDK" />
   <uses-library android:name="com.symbol.emdk" />_

Thanks guys for your input. Spent few hours trying to figure it out.

**Comment by metadevj** [comment]
To resolve error message:

`Installation failed due to: 'Failed to commit install session 2080962618 with command cmd package install-commit 2080962618. Error: INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package app.xxx.xxx requires unavailable shared library com.symbol.emdk; failing!'`

Add the following line to AndroidManifest.xml 

` <uses-library android:name="com.symbol.emdk"
            android:required="false"/>`

**Comment by mathewjacobposten** [comment]
I am able to initialize it while I am running the app in Zebra device. But I cannot use this in a Unit Test class. I am using JUnit and when the EMDK library usage is used anywhere in my test case, I am getting the error. 

Is there a sample of Unit Test anywhere I can refer so that I can understand the proper way to use it?

**Comment by EddieCorreia** [comment]
Hi Jacob-

Sorry you're having trouble. If you would, please submit your question in the developer forum linked below:

https://developer.zebra.com/latest-discussions

Thank you for choosing Zebra products.

Best regards,
Eddie Correia

Digital Content Specialist, TechDocs
ZEBRA TECHNOLOGIES CORPORATION
***@***.***
techdocs.zebra.com
www.zebra.com
________________________________________
